server:
  port: 7000
spring:
  application:
    name: visitor-system
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.76.200.101:3306/visitor?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: root
    password: 123456
  # redis 配置
  redis:
    port: 6379
    host: 120.76.200.101
    database: 1
    password: 123456
    # 连接超时时间（毫秒）
    connect-timeout: 10000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
